version: '3'
services:
  database:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=1234
    networks:
      - database-network
  web:
    build: .
    volumes:
      - ./src:/usr/app/src
    ports:
      - '8080:8080'
      - '8000:8000'
    networks:
      - database-network
    depends_on:
      - database

networks:
  database-network:
    driver: bridge
