version: '3'
services:
  database:
    image: mysql:5.7
  environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE=databasecftv
  ports:
    - 3306:3306
  networks:
    - database-network

  web:
    build:
      context: .
      dockerfile: Dockerfiledev
      args:
        version: 1
    volumes:
      - ./target/classes/:/extra_class_path
      - ./src/main/webapp:/webapp_dir
    ports:
      - '8080:8080'
      - '8000:8000'
    networks:
      - database-network
    depends_on:
      - database

networks:
  database-network:
    driver: bridge
